### ISSUE TITLE
failed to run webapp on master

### ISSUE THREAD

**Issue by voznik** [ngx-plus/ngx-admin#20]
on latest `master`, after clean install there are several errors:
- webpack failed to compile
```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
@ngx-plus/webapp: Module build failed: 
@ngx-plus/webapp: @include btn(primary,$btn-primary-bg,$btn-primary-color);
@ngx-plus/webapp:                     ^
@ngx-plus/webapp:       Undefined variable: "$btn-primary-bg".
@ngx-plus/webapp:       in /home/voznik/workspace/ngx-admin/packages/ui/src/styles/_bootswatch.scss (line 96, column 22)
@ngx-plus/webapp: Error: 
@ngx-plus/webapp: @include btn(primary,$btn-primary-bg,$btn-primary-color);
@ngx-plus/webapp:                     ^
@ngx-plus/webapp:       Undefined variable: "$btn-primary-bg".
@ngx-plus/webapp:       in /home/voznik/workspace/ngx-admin/packages/ui/src/styles/_bootswatch.scss (line 96, column 22)
@ngx-plus/webapp:     at options.error (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/node-sass/lib/index.js:291:26)
@ngx-plus/webapp:  @ ./src/styles.scss 4:14-187
@ngx-plus/webapp:  @ multi ./src/styles.scss
```
  when I've disabled `@import 'bootswatch';` ->
- unable to load app in browser
```
Uncaught Error: Unexpected value '[object Object]' imported by the module 'CoreModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.es5.js:1690)
    at compiler.es5.js:15382
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js:15365)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary (compiler.es5.js:15307)
    at compiler.es5.js:15380
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js:15365)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (compiler.es5.js:26795)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26768)
```

**Comment by brannon-darby** [comment]
@voznik - are you sure you're using a fresh version of the repo?  i will keep looking into it, but everything is building fine for me.

**Comment by voznik** [comment]
@brannon-darby yes, I'm shure. my node version is v6.11.3, npm 5.4.2
should I provide any additional info about environment?
this is error on develop branch after rm -rf node_modules & npm install:
```
@ngx-plus/ngx-webapp: ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@ngx-plus/ngx-sdk/node_modules/@angular/core/core.d.ts, resolving symbol SDKBrowserModule in /home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@ngx-plus/ngx-sdk/src/index.ts, resolving symbol SDKBrowserModule in /home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@ngx-plus/ngx-sdk/src/index.ts
@ngx-plus/ngx-webapp:     at positionalError (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:25104:35)
@ngx-plus/ngx-webapp:     at simplifyInContext (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24947:27)
@ngx-plus/ngx-webapp:     at StaticReflector.simplify (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24961:13)
@ngx-plus/ngx-webapp:     at StaticReflector.annotations (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24391:41)
@ngx-plus/ngx-webapp:     at _getNgModuleMetadata (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
@ngx-plus/ngx-webapp:     at _extractLazyRoutesFromStaticModule (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
@ngx-plus/ngx-webapp:     at /home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
@ngx-plus/ngx-webapp:     at Array.reduce (native)
@ngx-plus/ngx-webapp:     at _extractLazyRoutesFromStaticModule (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
@ngx-plus/ngx-webapp:     at /home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
@ngx-plus/ngx-webapp:     at Array.reduce (native)
@ngx-plus/ngx-webapp:     at _extractLazyRoutesFromStaticModule (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
@ngx-plus/ngx-webapp:     at Object.listLazyRoutesOfModule (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
@ngx-plus/ngx-webapp:     at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
@ngx-plus/ngx-webapp:     at AotPlugin._getLazyRoutesFromNgtools (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@ngtools/webpack/src/plugin.js:207:44)
@ngx-plus/ngx-webapp:     at _donePromise.Promise.resolve.then.then.then.then.then (/home/voznik/workspace/ngx-admin/apps/webapp/node_modules/@ngtools/webpack/src/plugin.js:443:24)
@ngx-plus/ngx-webapp: webpack: Failed to compile.
@ngx-plus/ngx-webapp:     at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by voznik** [comment]
should have been run `lerna clean` after switching from `master` to `develop`

**Comment by brannon-darby** [comment]
@voznik - i have several enhancements locally - will push them to develop today.
